apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-crawler-configmap
data:
  CRAWLER_PORT: "8082"
  API_URL: "http://synergychat-api-service:8081"
  CRAWLER_KEYWORDS: love,hate,joy,sadness,anger,disgust,fear,surprise
